f = open("./uvm_codes/dut.v", "w")

f.write('module dut(input [19:0]a, output reg [19:0]q = 0);\n')
f.write('\n')
f.write('    // temp signals - output of block a\n')
f.write('    reg [19:0] a_out ;\n')
f.write('    wire [19:0] q = 0 ;\n')
f.write('\n')
f.write('    // temp signal - counter for block a\n')
f.write('    integer i,j = 0 ;\n')
f.write('\n')
f.write('    always @(posedge clk)\n')
f.write('    begin\n')
f.write('        if (!rst)\n')
f.write('        begin\n')
f.write('            a_out = 0;\n')
f.write('            q = 0 ;\n')
f.write('        end\n')
f.write('    end\n')
f.write('\n')
f.write('    assign q[19:0] = a[19:0];\n')
f.write('\n')
f.write('endmodule\n')

f.close()

#open and read the file after the appending:
f = open("./uvm_codes/dut.v", "r")
print(f.read())