f = open("./uvm_codes/packet.sv", "w")

f.write('import uvm_pkg::*;\n')
f.write('`include "uvm_macros.svh"\n')
f.write('\n')
f.write('class packet extends uvm_sequence_item;\n')
f.write('\n')
f.write('   // Include all the signals to randomize with rand bit keyword below.\n')
f.write('   rand bit   [19:0] a;\n')
f.write('   rand bit [19:0]  q;\n')
f.write('\n')
f.write('   // include all the UVM options for NOPACK OR UNPACK valued signals inside object_utils_begin and object_utils_end.\n')
f.write('   `uvm_object_utils_begin(packet)\n')
f.write('     `uvm_field_int(a, UVM_ALL_ON | UVM_NOPACK);\n')
f.write('     `uvm_field_int(q, UVM_ALL_ON | UVM_NOPACK);\n')
f.write('   `uvm_object_utils_end\n')
f.write('\n')
f.write('   function new (string name = "packet");\n')
f.write('      super.new(name);\n')
f.write('   endfunction\n')
f.write('\n')
f.write('   function string convert2string();\n')
f.write('     return $sformatf("Value for A block=%0h Valid signal for Q=%0h", a, q);\n')
f.write('   endfunction\n')
f.write('\n')
f.write('endclass: packet\n')

f.close()

#open and read the file after the appending:
f = open("./uvm_codes/packet.sv", "r")
print(f.read())