f = open("./uvm_codes/seq.sv", "w")

f.write('import uvm_pkg::*;\n')
f.write('`include "packet.sv"\n')
f.write('\n')
f.write('class seq extends uvm_sequence #(packet);\n')
f.write('\n')
f.write('     `uvm_object_utils(seq)\n')
f.write('\n')
f.write('     function new(string name="seq");\n')
f.write('         super.new(name);\n')
f.write('     endfunction\n')
f.write('\n')
f.write('  task body;\n')
f.write('    packet tx;\n')
f.write('    tx = packet::type_id::create("tx");\n')
f.write('    start_item(tx);\n')
f.write('    assert(tx.randomize());\n')
f.write('    tx.rst = 1 ;\n')
f.write('    finish_item(tx);\n')
f.write('  endtask\n')
f.write('\n')
f.write('endclass: seq\n')

f.close()

#open and read the file after the appending:
f = open("./uvm_codes/seq.sv", "r")
print(f.read())